language: php

sudo: false

matrix:
    include:
        - php: 5.6
        - php: 7
        - php: 7.1
        - php: 7.2
        - php: 7.3
    fast_finish: true

before_script:
  - if [ "$TRAVIS_PHP_VERSION" = "5.3.3" ]; then composer config disable-tls true; composer config secure-http false; fi
  - if [ "$deps" == "low" ]; then composer update --prefer-source --prefer-lowest --prefer-stable; fi
  - if [ "$deps" != "low" ]; then composer install --prefer-source; fi

script: ./vendor/bin/phpunit


after_success:
  - travis_retry php ./vendor/bin/php-coveralls -v --config .coveralls.yml -v;